[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
remappings = [
    "@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.2.0/",
    "account-abstraction/=dependencies/eth-infinitism-account-abstraction-0.7/",
    "simple-account/=dependencies/erc4337-simple-account-0.0.1/",
    "forge-std/=dependencies/forge-std-1.9.6/src/",
]

[dependencies]
forge-std = "1.9.6"
"@openzeppelin-contracts" = "5.2.0"
eth-infinitism-account-abstraction = "0.7"
erc4337-simple-account = { version = "0.0.1", url = "https://github.com/nikbhintade/erc4337-simple-account/archive/refs/tags/0.0.1.zip" }

[soldeer]
remappings_generate = true
remappings_regenerate = false
remappings_version = false
remappings_location = "config"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
