[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
remappings = [
    "@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.2.0/",
    "account-abstraction/=dependencies/eth-infinitism-account-abstraction-0.7/",
    "forge-std/=dependencies/forge-std-1.9.6/src/",
]

[dependencies]
forge-std = "1.9.6"
"@openzeppelin-contracts" = "5.2.0"
eth-infinitism-account-abstraction = "0.7"

[soldeer]
remappings_generate = true
remappings_regenerate = false
remappings_version = false
remappings_location = "config"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
